spring:
  datasource:
    url: "jdbc:mysql://db:3306/sa_rest?autoReconnect=true&useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8&createDatabaseIfNotExist=true"
    username: "root"
    password: ""
    continueOnError: true
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    hikari:
      connection-test-query: SELECT 1
  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQL8Dialect
logging:
  level:
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
