version: '3.3'

services:
  db:
    image: mysql:8.0
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: sa_rest
      MYSQL_USER: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

  sample:
    depends_on:
      - db
    image: evelin/docker-sample:v1
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/sa_rest?autoReconnect=true&useSSL=false
    ports:
      - "8080:8080"

volumes:
  db_data: {}
